export const COLLECTIONS = {
  USERS: "users",
  QT_ENTRIES: "qt_entries",
  BIBLE_FAVORITES: "bible_favorites",
  BIBLE_HISTORY: "bible_history",
  ANNOUNCEMENTS: "announcements",
  EVENTS: "events",
  PRAYER_REQUESTS: "prayer_requests",
  BULLETINS: "bulletins",
  PLAYLISTS: "playlists",
  ATTENDANCE: "attendance",
  NOTIFICATIONS: "notifications",
  AUDIT_LOGS: "audit_logs",
  MINISTRIES: "ministries",
  CELL_GROUPS: "cell_groups",
  SERMONS: "sermons",
  TEAMS: "teams",
  CELLS: "cells",
  ORGANIZATION_SETTINGS: "organization_settings",
  DAILY_CONTENT: "daily_content",
} as const;

export type CollectionName = (typeof COLLECTIONS)[keyof typeof COLLECTIONS];

export const COLLECTION_LABELS: Record<CollectionName, string> = {
  [COLLECTIONS.USERS]: "사용자",
  [COLLECTIONS.QT_ENTRIES]: "QT",
  [COLLECTIONS.BIBLE_FAVORITES]: "성경 즐겨찾기",
  [COLLECTIONS.BIBLE_HISTORY]: "성경 최근 기록",
  [COLLECTIONS.ANNOUNCEMENTS]: "공지사항",
  [COLLECTIONS.EVENTS]: "일정",
  [COLLECTIONS.PRAYER_REQUESTS]: "기도제목",
  [COLLECTIONS.BULLETINS]: "주보",
  [COLLECTIONS.PLAYLISTS]: "재생목록",
  [COLLECTIONS.ATTENDANCE]: "출석",
  [COLLECTIONS.NOTIFICATIONS]: "알림",
  [COLLECTIONS.AUDIT_LOGS]: "감사록",
  [COLLECTIONS.MINISTRIES]: "사역",
  [COLLECTIONS.CELL_GROUPS]: "셀 그룹",
  [COLLECTIONS.SERMONS]: "설교",
  [COLLECTIONS.TEAMS]: "팀",
  [COLLECTIONS.CELLS]: "순",
  [COLLECTIONS.ORGANIZATION_SETTINGS]: "조직 설정",
  [COLLECTIONS.DAILY_CONTENT]: "오늘의 콘텐츠",
};
